### ISSUE TITLE
Start over?

### ISSUE THREAD

**Issue by drwetter** [secdec/attack-surface-detector-burp#2]
Hi,

thanks for the burp plugin. 

How can I just make the plugin forget everything? I was importing the source but forgot to add the path from the application server.

Cheers, Dirk

**Comment by hoodoer** [comment]
Dirk,

I don't have a burp install handy, but I'd imagine if you go to the
extender tab and unload/reload the attack surface detector plugin it would
reset it to baseline.


-Drew

**Comment by drwetter** [comment]
Hey Drew,

nah, that's what I tried too. As soon as I reinstall the plugin under options the previous values are restored, that is maybe another issue as I was expecting at least then to start from scratch.

If I click on import source also the dialog box is filled in (with a correct path as I corrected it) but the endpoints are not corrected and still absolute 

Cheers, Dirk

**Comment by matthewD-AVI** [comment]
Currently there is no way to reset your setting to default. ASD was designed to have settings persist on uninstall so that updates would not rewrite settings. If this is something you really need feel free to make changes and create a pull request. If not I will try and find some of my own time to add a button to revert to default settings.
